# Generated by Django 5.0.6 on 2024-06-29 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=40)),
                ('data', models.DateTimeField()),
                ('unidade', models.CharField(choices=[('UN', 'Unidade'), ('PR', 'Par'), ('PC', 'Peca'), ('MT', 'Metro')], default='UN', max_length=2)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('reservado', models.CharField(max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
