# Generated by Django 5.0.6 on 2024-06-30 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='unidade',
            field=models.CharField(choices=[('UN', 'Unidade'), ('PR', 'Par'), ('PC', 'Peca'), ('MT', 'Metro'), ('KG', 'Kilo'), ('CX', 'Caixa'), ('DZ', 'Duzia'), ('RL', 'Rolo'), ('PT', 'Pacote'), ('CT', 'Cartela'), ('G', 'Grama'), ('L', 'Litro'), ('m3', 'Metro cúbico'), ('ml', 'Mililitro')], default='UN', max_length=2),
        ),
    ]
