# Generated by Django 5.0.6 on 2024-07-18 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_alter_produtos_unidade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtos',
            options={},
        ),
    ]
