# Generated by Django 5.0.6 on 2024-07-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_alter_produtos_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='mostrar',
            field=models.BooleanField(default=True),
        ),
    ]
