# Generated by Django 5.0.6 on 2024-08-09 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0007_produtos_fabrica'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtos',
            options={'ordering': ('id',), 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
    ]
