# Generated by Django 5.0.6 on 2024-08-24 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0009_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
