# Generated by Django 5.0.6 on 2024-08-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fabrica', models.CharField(max_length=40)),
                ('cnpj_fabrica', models.CharField(max_length=18)),
                ('ie_fabrica', models.CharField(max_length=12)),
                ('cep_fabrica', models.CharField(max_length=10)),
                ('endereco_fabrica', models.CharField(max_length=30)),
                ('numero', models.IntegerField(verbose_name=4)),
                ('complemento', models.CharField(max_length=8)),
                ('bairro_fabrica', models.CharField(max_length=30)),
                ('cidade_fabrica', models.CharField(max_length=30)),
                ('telefone_fabrica', models.CharField(max_length=12)),
                ('email_fabrica', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
