# Generated by Django 5.0.6 on 2024-08-09 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabrica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabrica',
            options={'ordering': ('id',), 'verbose_name': 'fabrica', 'verbose_name_plural': 'fabricas'},
        ),
    ]
